services:
    backend:
        container_name: "backend"
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - HOST=0.0.0.0
        volumes:
            - .:/apps/backend
            - /apps/backend/node_modules
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "3333:3333"
        networks:
            - default

networks:
    default:
        driver: bridge
